name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  addon:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@main
    secrets: inherit 