name: "Solar Optimiser"
version: "0.1.0"
slug: "solar_optimiser"
description: "A Home Assistant add-on to optimize solar panel usage and energy management"
url: "https://github.com/chrismelba/solar-optimiser"
arch:
  - amd64
init: false
panel_icon: mdi:solar-power
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]"
options:
  solar_entity: ""
  grid_entity: ""
  battery_entity: ""
  battery_capacity: 10
schema:
  solar_entity: str
  grid_entity: str
  battery_entity: str
  battery_capacity: float
image: "local/solar-optimiser/{arch}" 