# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Solar Optimiser
version: "1.0.0"
slug: solar-optimiser
description: Solar optimization add-on for Home Assistant
url: "https://github.com/chrismelba/solar-optimiser/tree/main/solar"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8080/tcp: 8080
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/chrismelba/{arch}-addon-solar-optimiser"
