name: "Build and Publish"
on:
  push:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./solar-optimiser
          platforms: linux/${{ matrix.arch }}
          push: true
          build-args: |
            BUILD_FROM=homeassistant/${{ matrix.arch }}-base
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.arch }}-solar-optimiser:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.arch }}-solar-optimiser:0.1.0 